print("***************`a02_components.R`***************")

###############################################################################
# Load input files
dataset <- readr::read_csv(file.path(
  settings$metadata$bibliometrics_folder,
  settings$metadata$project_folder,
  settings$metadata$filtered_folder,
  "dataset_raw_cleaned.csv"
))

network <- readr::read_csv(file.path(
  settings$metadata$bibliometrics_folder,
  settings$metadata$project_folder,
  settings$metadata$filtered_folder,
  settings$cno$network_type,
  "network.csv"
))

###############################################################################
###############################################################################
###############################################################################
# Aux. function to map components from the largest.
reorder_memberships <- function(membership) {
  # Create a table of group sizes
  group_sizes <- table(membership)

  # Create a named vector for the mapping
  # Sort group sizes in descending order and get original group numbers
  size_order <- order(group_sizes, decreasing = TRUE)

  # Create mapping from old to new membership numbers
  mapping <- seq_along(group_sizes)
  names(mapping) <- names(group_sizes)[size_order]

  # Apply the mapping to the original membership vector
  new_membership <- mapping[as.character(membership)]

  return(new_membership)
}

# Component selection
# Create the network object and retain the largest component
g1 <- graph_from_data_frame(network, directed = TRUE)

# Get components
components_membership <- components(g1)
components_membership$new_membership <- reorder_memberships(components_membership$membership)
components_sizes <- table(components_membership$new_membership)
components_available <- length(components_sizes)

# Get components df
components_df <- data.frame(
  "node_ids" = c(1:length(components_membership$new_membership)),
  "X_N" = V(g1) %>% names() %>% as.numeric(),
  "component" = components_membership$new_membership
)

# Get the network based on strategy
if (settings$cno$component$strategy == "top") {
  valid_nodes <- which(components_df$component <= settings$cno$component$value)
  g_valid <- subgraph(g1, valid_nodes)
}

if (settings$cno$component$strategy == "component") {
  valid_nodes <- which(components_df$component == settings$cno$component$value)
  g_valid <- subgraph(g1, valid_nodes)
}


if (settings$cno$component$strategy == "min_vertices") {
  valid_components <- components_sizes[components_sizes > settings$cno$component$value] %>%
    names() %>%
    as.integer()
  valid_nodes <- which(components_df$component == valid_components)
  g_valid <- subgraph(g1, valid_nodes)
}

if (settings$cno$component$strategy == "all") {
  g_valid <- g1
}


###############################################################################
# Valid ids are those in the largest component, else are orphans
valid_vertices <- V(g_valid) %>%
  names() %>%
  as.numeric()

# Backups
dataset_backup <- dataset # backup
network_backup <- network

# Save orphans
orphans <- dataset %>% filter(!(X_N %in% valid_vertices))

# Order dataset to the order of nodes in the network
dataset <- dataset %>% filter(X_N %in% valid_vertices)
dataset <- dataset[match(valid_vertices, dataset$X_N), ]

# Filter the network to have only nodes in the selected network
network <- network[network$V1 %in% valid_vertices, ]
network <- network[network$V2 %in% valid_vertices, ]


# ttt1 <- graph_from_data_frame(network, directed = FALSE)
# ttt2 <- graph_from_data_frame(network, directed = FALSE)

###############################################################################
###############################################################################
###############################################################################
# Save the file
# From the pov of this very code, this is actually the output folder. Where the files generated by this code will be placed.
results_folder_path <- file.path(
  settings$metadata$bibliometrics_folder,
  settings$metadata$project_folder,
  settings$metadata$analysis_id
)

# Write the dataset
write.csv(dataset,
  file = file.path(results_folder_path, "dataset_comp.csv"),
  row.names = FALSE
)

# Write orphans
write.csv(orphans,
  file = file.path(results_folder_path, "orphans.csv"),
  row.names = FALSE
)

# Write Network
write.csv(network,
  file = file.path(results_folder_path, "network_comp.csv"),
  row.names = FALSE
)

# Write Components
write.csv(components_df,
  file = file.path(results_folder_path, "components.csv"),
  row.names = FALSE
)

# The components settings and info
settings_save <- list(
  components = settings$cno$component,
  components_found = components_available,
  components_sizes = components_sizes
)
writeLines(
  RJSONIO::toJSON(settings_save,
    pretty = TRUE,
    auto_unbox = TRUE
  ),
  file.path(results_folder_path, "component_settings.json")
)

# Clear environment
rm(list = setdiff(ls(), "settings"))
