print("***************`a03_clustering.R`***************")

# 20180323 -> 20220526 -> 20221220
# Framework for Citation Network Analysis with Recursive Clustering, or Topic Models.

# Input.
# A dataset having:
# - Web of Science formatted file (header and columns)

# Output
# A `dataset.rdata` object
# Being the same input dataset but with the "X_C" column.

###############################################################################
# Read input files
analysis_folder_path <- file.path(
  settings$metadata$bibliometrics_folder,
  settings$metadata$project_folder,
  settings$metadata$analysis_id
)

dataset <- readr::read_csv(file.path(
  analysis_folder_path,
  glue("dataset_comp.csv")
))
orphans <- readr::read_csv(file.path(
  analysis_folder_path,
  glue("orphans.csv")
))
network <- readr::read_csv(file.path(
  analysis_folder_path,
  glue("network_comp.csv")
))

###############################################################################
###############################################################################
###############################################################################
# Document classification (Get clusters or Get topics)
if (settings$params$type_of_analysis %in% c("citation_network", "both")) {
  source(file.path(getwd(), "02_citation_network", "00_citation_network_clustering.R"))
}

# Auxiliary code to find the right number of clusters. And update the threshold.
# Get the clusters collecting 90% of papers or the top 10, whatever is the smallest number.
table(dataset_minimal$X_C) %>%
  sort(decreasing = TRUE) %>%
  prop.table() %>%
  cumsum() %>%
  plot()
table(dataset_minimal$X_C) %>%
  sort(decreasing = TRUE) %>%
  prop.table() %>%
  cumsum()
table(dataset_minimal$X_C) %>%
  sort(decreasing = TRUE) %>%
  plot()
table(dataset_minimal$X_C)
# Update the threshold in settings file.

###############################################################################
###############################################################################
##############################################################################
# Save the file
# From the pov of this very code, this is actually the output folder. Where the files generated by this code will be placed.
results_folder_path <- file.path(
  settings$metadata$bibliometrics_folder,
  settings$metadata$project_folder,
  settings$metadata$analysis_id,
  settings$cno$clustering$algorithm
)
dir.create(results_folder_path, showWarnings = FALSE)

# Write the `dataset_minimal` which is created in 02_citation_network/02_louvain_Infomap.R
write.csv(dataset_minimal,
  file = file.path(results_folder_path, "dataset_clustered.csv"),
  row.names = FALSE
)

# The components settings and info
network_description$algorithm <- settings$cno$clustering$algorithm
network_description$clusters_found <- dataset$X_C %>%
  unique() %>%
  length()

writeLines(
  RJSONIO::toJSON(network_description,
    pretty = TRUE,
    auto_unbox = TRUE
  ),
  file.path(results_folder_path, "network_settings.json")
)

# Clear environment
rm(list = setdiff(ls(), "settings"))

# # ========================================================================
# # Create the summary
# source(file.path(getwd(), "03_reports", "03_general_summary.R"))

# # Orphans treatment
# if (settings$addons$include_orphans == "99" | settings$addons$include_orphans == "999") {
#   source(file.path(getwd(), "zz_utils", "zz-append_orphans.R"))
# }
#
# # Add-ons
# if (settings$params$type_of_analysis == "citation_network" &
#     exists('g1') &
#     (settings$addons$page_rank | settings$addons$eigen_centrality | settings$addons$closeness_centrality | settings$addons$betweeness_centrality)) {
#   source(file.path(getwd(), "zz_utils", "zz-centrality_meassures.R"))
# }
# file.path(report_path, "dataset_clustering.csv")
