print("***************`a04_thresholding.R`***************")

###############################################################################
# Read input files
analysis_folder_path <- file.path(settings$metadata$bibliometrics_folder,
                                  settings$metadata$project_folder,
                                  settings$metadata$analysis_id)

network <- readr::read_csv(file.path(analysis_folder_path, "network_comp.csv"))
dataset_minimal <- readr::read_csv(file.path(analysis_folder_path, 
                                             settings$cno$clustering$algorithm,
                                             "dataset_clustered.csv"))

# Create network object
if (!settings$cno$using_mission_pairs_from_fukan) {
  print("Loading computed network")
  g1 <- graph_from_data_frame(network, directed = TRUE)
} else {
  # The network object is based on "mission.pairs.tsv" from Fukan's results
  print("Graph from mission pairs")
  g1 <- read.graph(network, format = "ncol")
}

# Verification
stopifnot(
  all(dataset_minimal$X_N == V(g1)$name)
)

###############################################################################
###############################################################################
###############################################################################
source("02_citation_network/03_recursive_clustering_WOS.R")

###############################################################################
###############################################################################
###############################################################################
# Save the file
# From the pov of this very code, this is actually the output folder. Where the files generated by this code will be placed.
results_folder_path <- file.path(settings$metadata$bibliometrics_folder,
                                 settings$metadata$project_folder,
                                 settings$metadata$analysis_id,
                                 settings$cno$clustering$algorithm,
                                 settings$cno$thresholding$threshold %>% as.character())
dir.create(results_folder_path, showWarnings = FALSE)

# Write the `dataset_minimal` which is created in 02_citation_network/02_louvain_Infomap.R
write.csv(dataset_minimal, 
          file = file.path(results_folder_path, "dataset_minimal.csv"), 
          row.names = FALSE)

# The components settings and info
writeLines(RJSONIO::toJSON(settings$cno$thresholding, 
                           pretty = TRUE,
                           auto_unbox = TRUE),
           file.path(results_folder_path, "threshold_settings.json"))

# Print info to the console:
print(dataset_minimal$level0 %>% unique() %>% sort())
print(glue("Clusters: {dataset_minimal$level0 %>% unique() %>% length()}"))

print(dataset_minimal$subcluster_label1 %>% unique() %>% sort())
print(glue("Clusters: {dataset_minimal$subcluster_label1 %>% unique() %>% length()}"))

# Clear environment
rm(list = setdiff(ls(), "settings"))
