# Dataset treatment for Fukan System datasets

# Inputs:
# - Path to the folder having the `mission.facet.all.tsv` and `mission.facet.orphans.tsv`
# - Path to the folder with the `mission.pairs.tsv` file

# Output:
# - dataset.csv and orphans.csv properly formatted for my topic analyzer
# - copy of mission.pairs.tsv as network.csv
# - all saved to the `/inputs` folder

# "Properly formatted" means to remove unnecessary columns, check column types, and check column headers.
base::file.choose()
###########################################################################################
# OPTIONS
###########################################################################################
## Select the input folders:
project_folder <- choose.dir()

## Query_id
## This has de form Qxxx whith the query number from the query control file
dataset_metadata <- list(
  "query_id" = "Q295",
  "fukan_url" = "NA"
)


###########################################################################################
# RUN FROM HERE
###########################################################################################
## Libraries
source("zz_utils/02_libraries.R")
source(file.path(getwd(), "zz_utils", "read_from_fukan_function.R"))

## Path to `/inputs`
# Here 'input' refer to the inputs for clustering.
# From the pov of this very code, this is actually the output folder. Where the files generated by this code will be placed.
bibliometrics_folder <- "C:\\Users\\crist\\OneDrive\\Documentos\\03-bibliometrics"
dir.create(file.path(bibliometrics_folder, dataset_metadata$query_id), showWarnings = FALSE)

#################################################
# dataset and orphans
#################################################

## Read files
dataset <- read_from_fukan_2(project_folder)
orphans <- read_from_fukan_2(project_folder, what = "orphans")

#################################################
# Using Fukan Sub Clusters as Cluster 0
#################################################

library(glue)
fukan_clusters <- table(dataset$X_C)
initial_cluster <- 1
final_cluster <- 26
total_clusters <- length(fukan_clusters)

main_cluster <- initial_cluster
sub_cluster <- 1
sub_cluster_labels <- c("1-1")
for (j in c(2:length(fukan_clusters))) {
  if (fukan_clusters[j] <= fukan_clusters[j - 1] &
    main_cluster <= final_cluster) {
    main_cluster <- main_cluster
    sub_cluster <- sub_cluster + 1
  } else {
    main_cluster <- main_cluster + 1
    if (main_cluster <= final_cluster) {
      sub_cluster <- 1
    } else {
      sub_cluster <- 0
    }
  }
  sub_cluster_labels <- c(sub_cluster_labels, glue("{main_cluster}-{sub_cluster}"))
  print(glue("{main_cluster}-{sub_cluster}"))
}

sub_cluster_labels

dataset$fukan_subcluster_label <- sub_cluster_labels[dataset$X_C]
table(dataset$fukan_subcluster_label, dataset$X_C)

# reorder clusters from largest like in cluster 0
tmp <- table(dataset$X_C)
if (!(sapply(c(2:length(tmp)), function(x) {
  tmp[x] <= tmp[x - 1]
}) |> all())) {
  tmp <- table(dataset$X_C) |> sort(decreasing = TRUE)
  dataset$fukan_original_cluster_id <- dataset$X_C
  dataset$X_C <- match(dataset$X_C, names(tmp))
}

# Verify clusters are ordered from the largest
table(dataset$X_C)

#################################################
# Save and FINISH!
# Or skip and add the network.
#################################################

## Create directories
save(dataset, orphans, dataset_metadata,
  file = file.path(bibliometrics_folder, dataset_metadata$query_id, "dataset.rdata")
)




#################################################
# network ncol file
#################################################
# NOTE:
# we do not need the network object if we create the reports based on the Fukan System X_C clusters.
# Skip this section if that's the case.

#################################################
# OPTION 1: Use the ncol file from Fukan System
# In Fukan System the network file only appears when using the Newman algorithm
# So if we plan to recursive clustering. we should first create an analysis with the Newman algorithm.

## Read files
network_folder <- choose.dir()
network <- fread(paste(network_folder, "\\mission.pairs.tsv", sep = ""), sep = "\t")

#################################################
# OPTION 2: Create our own ncol file.

# To be done.
# The code is already done but we need to incorporate it in this folder.

## Create directories
save(dataset, orphans, network, dataset_metadata,
  file = file.path(bibliometrics_folder, dataset_metadata$query_id, "dataset.rdata")
)

## Clear environment
if (file.exists(file.path(bibliometrics_folder, dataset_metadata$query_id, "dataset.rdata"))) {
  # rm(list = (setdiff(ls(), c("dataset", "orphans", "network", "dataset_metadata"))))
  rm(list = (ls()))
}
